### ISSUE TITLE
Can we turn off the isExposed flag in the meta?

### ISSUE THREAD

**Issue by Manish-Padakanti** [avonni/base-components#257]
I want to use the base-components internally in my salesforce managed package by deploying all the components as part of my package. With the `isExposed` flag turned on I would have to go through a security review from salesforce if I ever plan to delete them in the future. Do you plan to not expose these base components in the future?

**Comment by jbverger** [comment]
Hi Manish-Padakanti, base components should not be exposed. The flag isExposed has been set to false for all components. Thanks,
