### ISSUE TITLE
Doubt on lightning-focus-trap

### ISSUE THREAD

**Issue by liumiaowilson** [avonni/base-components#642]
Hi,
I'm very interested in avonni base-components and have been watching this repo for quite some time. Meantime I keep learning to code from all these wonderful components. Recently I have a doubt on the usage of lightning-focus-trap component appeared in the codebase. 
In this PR https://github.com/avonni/base-components/commit/ffad404c13a7c7992771106f7afb7484a84db256, we can see lightning-focus-trap used in tabBar component. I tried to use the same in my custom web component, but it throws this error: No MODULE named lightning:focusTrap found.
I've been searching on this for a while but could not find anything helpful. Can anyone shed some light on this?

Thanks in advance.

**Comment by jbverger** [comment]
Hi,

You're right, the module lightning-focus-trap doesn't operate properly on the Salesforce Platform. We've just introduced the avonni-focus-trap module and have replaced the current lightning-focus-trap with avonni-focus-trap. Now, you should be able to deploy it to Salesforce.

Thanks,

**Comment by liumiaowilson** [comment]
Thank you for working on avonni-focus-trap. However, when I was on a trial with Avonni Screen Components, I noticed lightning-focus-trap component is also used in these screen components/custom property editors. Just wondering how you managed to deploy lightning-focus-trap with avonni components.
